### ISSUE TITLE
Wintert Symposium Photos 

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/winter-symposium#2]
@AlexanderElias can you please take a look at the photos section on Symposium site and setup that slideshow for 2015 Symposium event. They may want to add 2016 event in the future too for your information if they can ever get their stuff together for that. In any case, those photos are in cloudinary. Let me know if you have any questions.

**Comment by AlexanderElias** [comment]
@mountaingoat69  working on it now.

**Comment by AlexanderElias** [comment]
@mountaingoat69 photos gallery viewer fixed. Added the gallery page.

**Comment by mountaingoat69** [comment]
Look sweet! Thanks dude.
