### ISSUE TITLE
Formspree

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/winter-symposium#6]
@AlexanderElias 

Hey man, 

For some reason I'm getting an error message when trying to retrieve forms from formspree website for Winter Symposium. Please let me know if you see the same thing. 

<img width="1293" alt="screen shot 2016-12-05 at 3 21 50 pm" src="https://cloud.githubusercontent.com/assets/22133400/20905003/478b39f6-baff-11e6-9675-f4429edc513c.png">

**Comment by AlexanderElias** [comment]
That is weird. It is probably as it suggest though. Must be that there server is overloaded. Did this happen when you logged in to view past forms?

**Comment by mountaingoat69** [comment]
The weird thing is that it's only doing it for Symposium site, not for any
other form submissions for different sites.

**Comment by mountaingoat69** [comment]
Sorry, and to clarify, the issue presents itself when logged into formspree
account and when I go to retrieve past submitted forms.

**Comment by TheBurnsby** [comment]
@AlexanderElias were you able to look into this? I think its safe to rule out this isnt a temporary issue, as it is still not working. Should we delete whats there, and re create the form in formspree?

**Comment by AlexanderElias** [comment]
@mountaingoat69 @TheBurnsby 

I contacted form spree support and I am waiting to hear back about whats going on with this form. Something is wrong on there end. We could delete the form and recreate it but if the forms are still submitting just fine we should probably just wait until I hear back from them. Last time they got back to me really quick so they will probably send me an email tomorrow.

**Comment by mountaingoat69** [comment]
Thanks for the update Alex!

**Comment by mountaingoat69** [comment]
The form issue is persisting. I'm not certain formspree has gotten back with you yet Alex, but I think it's best given the importance of the forms that if we cannot arrive at a solution to just set them up with their own account. I also think we should setup Rose House with their own account too. My two cents. Thanks.

**Comment by AlexanderElias** [comment]
Switched to new form service.
