### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/winter-symposium#7]
Hey guys, 

We need a login page for the Winter Symposium site. This section will have presentation forms that are only accessible to Symposium attendees. So, once logged in attendees will be able to download those presentations or access from their phones. Therefore, our job is to create a login page accessible with a generic username and password so that attendees can download these forms once logged in. We need to have this up and running at the top of the "Information" tab menu items by January 1st. @TheBurnsby @AlexanderElias 

Thanks, 
Brandon

**Comment by TheBurnsby** [comment]
Can we discuss other options for this? I don't think a log in page is necessary. Maybe a direct link can be made to the downloads page and emailed to only the appropriate people?

**Comment by TheBurnsby** [comment]
@AlexanderElias Just a reminder, based on what we talked about Sunday.

**Comment by AlexanderElias** [comment]
@mountaingoat69 @TheBurnsby 

Login page is created I will send the credentials via email.

**Comment by AlexanderElias** [comment]
I created a login page we just need files to upload. Then they will be available.
