### ISSUE TITLE
Symposium Handouts/ Login Page

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/winter-symposium#8]
Hey @AlexanderElias I recently created a new folder in cloudinary for Symposium login page titled Login-Page-Handouts. I'm sure we will get more handouts moving forward, but I recently uploaded several of those pdf files. 

Can you make the login page live and add those pdf files as well? When done, please send me login name/ password to share with Sandy at Winter Symposium. 

Thanks,
B

**Comment by AlexanderElias** [comment]
@mountaingoat69 

Got the page linked in the cspaws.com navigation. Also added all the files. I sent the username and password for the login to your webcab email address.
